### ISSUE TITLE
FireCoronaSize is using MediumGrassDistMult's setting

### ISSUE THREAD

**Issue by dbozan99** [JuniorDjjr/SA-MixSets#2]
if (ReadIniFloat(ini, &lg, "Graphics", "MediumGrassDistMult", &f)) {
		G_MediumGrassDistMult = f;
		WriteMemory<float*>(0x5DAD88 + 2, &G_MediumGrassDistMult, true);
	}

	if (ReadIniFloat(ini, &lg, "Graphics", "FireCoronaSize", &f)) {
		G_MediumGrassDistMult = f;
		WriteMemory<float*>(0x53B784 + 2, &G_MediumGrassDistMult, true);
	}

**Comment by dbozan99** [comment]
I was looking at the code again today when I realized that my title is wrong, the first G_MediumGrassDistMult goes out of scope (and even if it didn't it gets overwritten and never used again anyway), so FireCoronaSize is working as intended. It's just a typo.

**Comment by JuniorDjjr** [comment]
The problem is with MediumGrassDistMult, it overwrites it.

**Comment by JuniorDjjr** [comment]
Fixed.
