### ISSUE TITLE
Problemas em algumas missões relacionados à opção "WeaponRangeMult"

### ISSUE THREAD

**Issue by ghost** [JuniorDjjr/SA-MixSets#3]
Peço desculpas se este não for o local apropriado, mas procurei um pouco e não encontrei outra forma de reportar isto.

Por acaso estava jogando GTA SA, fazendo algumas missões, e durante uma delas, a primeira do OG Loc, notei que a moto estava perdendo durabilidade muito rápido ao levar tiros. Até aí tudo bem, consegui contornar o problema e seguir em frente, mas ao chegar na missão "Just Business" do Big Smoke, a coisa complicou um pouco mais.

Nessa missão eu tinha que matar alguns russos, mas antes mesmo de poder mirar em algum deles, a vida do Smoke já estava descendo. 3 ou 4 segundos depois, sua vida estava na metade. Com alguma sorte, eu consegui matar todos, mas com a vida que restou, não dava para prosseguir e matar os outros personagens do lado de fora. Tentei mais algumas vezes crente de ser um problema meu, mas eventualmente conclui que era culpa de algum mod.

O resto é conversa. Fui desativando mods e tentando isolar o "culpado" até chegar no MixSets e na configuração certa. **Eu estou usando o ".ini" padrão do mod, apenas com correções, e consegui resolver o problema depois de reduzir o multiplicador de "WeaponRangeMult" para os valores padrões do jogo (de 4.0 para 1.0).**

Decidi reportar pois sei que vocês se preocupam bastante com a integridade do jogo e das missões, pensei que talvez tivessem interesse em mexer no ".ini" ao saber disso. Bom, não sei, mas deixo aqui este report de toda forma.

**Comment by JuniorDjjr** [comment]
A função foi movida para o mod Peds Skills, lá há como ajustar melhor sem quebrar o gameplay.
